[package]
name = "mongodb_cmd"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = "1.48.0"
mongodb = "3.4.1"
dotenvy = "0.15.7"
anyhow = "1.0.100"
actix-web = "4.12.1"
serde = "1.0.228"
serde_json = "1.0.147"
url = "2.5.7"
futures = "0.3.31"
